# Generated by Django 4.1.3 on 2022-12-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
