# Generated by Django 4.1.3 on 2022-12-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_hashtags_post_hashtags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hashtags',
            new_name='hashtag',
        ),
    ]
