# Generated by Django 4.1.3 on 2022-12-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_hashtags_post_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
